version: '3.8'

services:
  biblioteca-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-front
    ports:
      - "9505:9505"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9505
    restart: always
